#ifndef LAB5_PIPEREQUESTTYPE_H
#define LAB5_PIPEREQUESTTYPE_H

enum PipeRequestType {
    PIPE_REQUEST_READ = 1,
    PIPE_REQUEST_BEGIN_MODIFY = 2,
    PIPE_REQUEST_COMMIT_MODIFY = 3,
    PIPE_REQUEST_END_ACCESS = 4,
    PIPE_REQUEST_SHUTDOWN = 5
};

#endif
