#ifndef LAB5_PIPERESPONSESTATUS_H
#define LAB5_PIPERESPONSESTATUS_H

enum PipeResponseStatus {
    PIPE_RESPONSE_OK = 0,
    PIPE_RESPONSE_NOT_FOUND = 1,
    PIPE_RESPONSE_ERROR = 2,
    PIPE_RESPONSE_INVALID_STATE = 3
};

#endif
